---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ron2cuba/lenouvel.me/
    # Déploiement du front Symfony (public)
    - /bin/cp -R public/* $DEPLOYPATH
    # (Optionnel) Déploiement de fichiers de config spécifiques
    # - /bin/cp .htaccess $DEPLOYPATH
    # (Optionnel) Installation des dépendances PHP (si composer dispo côté serveur)
    # - cd /home/ron2cuba/lenouvel.me && /opt/cpanel/ea-php82/root/usr/bin/php /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader