version: '3.8'

services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8001:80
    networks:
      - home-cloud-network

  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    networks:
      - home-cloud-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_USER: symfony
      PMA_PASSWORD: symfony
    ports:
      - 8080:80
    networks:
      - home-cloud-network

networks:
  home-cloud-network:
    driver: bridge