

# Expose services needed in tests via static::getContainer()->get()
when@test:
    services:
        Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface:
            alias: security.password_hasher
            public: true

        App\Tests\EventListener\TestAuthorizationListener:
            tags:
                - { name: kernel.event_subscriber }

        App\Service\File\StorageService:
            public: true
            arguments:
                $storageDir: '%app.storage_dir%'

        App\Interface\File\StorageServiceInterface:
            alias: App\Service\File\StorageService
            public: true

        App\Tests\Fake\FakeChangelogFetcher: ~

        App\Interface\GitHub\ChangelogFetcherInterface:
            alias: App\Tests\Fake\FakeChangelogFetcher
            public: true
